/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shannon_bmobmusic_MyApplication */

#ifndef _Included_com_example_shannon_bmobmusic_MyApplication
#define _Included_com_example_shannon_bmobmusic_MyApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shannon_bmobmusic_MyApplication
 * Method:    getBmobKeyFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_shannon_bmobmusic_MyApplication_getBmobKeyFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
